### ISSUE TITLE
关于程序中使用的ImagePool

### ISSUE THREAD

**Issue by Shecyy** [eezkni/UEGAN#13]
老师，您好，您在代码中使用了ImagePool，请问这个类的作用是什么哇？

**Comment by eezkni** [comment]
以一定的概率将之前增强的照片输入到辨别器，具体可以参考文章“Learning from Simulated and Unsupervised Images through Adversarial Training”的Section 2.3

**Comment by Shecyy** [comment]
非常感谢老师您的回复，看了您推荐的这篇CVPR，直接秒懂了这个ImagePool的设计意义。yyds

**Comment by Shecyy** [comment]
老师，您好，请问这个论文，可以直接适用于低光照图像增强吗？比如LOL数据集。还是说需要调整生成器的三个Loss的参数之后才可以？或者其他？

**Comment by eezkni** [comment]
我没有测试该模型在LOL数据集上的性能，如果你感兴趣可以对loss以及模型结构进行相应的修改然后测试一下在LOL数据集上的性能
