### ISSUE TITLE
UEGAN-FiveK_rahinge_92.0.pth is missing

### ISSUE THREAD

**Issue by Liampour** [eezkni/UEGAN#14]
Hello,
Congratulation for your awesome work!
when I am trying to run main.py an error occurred.

>  No such file or directory: './results\\UEGAN-FiveK\\models\\UEGAN-FiveK_rahinge_92.0.pth

**Comment by eezkni** [comment]
Please follow the instructions in the "Testing" section of the README to download the pre-trained model.

**Comment by Liampour** [comment]
Sorry for the inconvenience. 
Thank you very much for your answer!

**Comment by Liampour** [comment]
When I am trying to run the code another error occurs in data_loader.py line 69

> in __getitem__    _, img_name = img_name.rsplit('/', 1)

> not enough values to unpack (expected 2, got 1)

I think this happens because  in img_name contains this character \ instad of this /   img_name =str(data\fivek\test\raw\a4670-Duggan_080115_4464.png) instead of str(data/fivek/test/raw/a4670-Duggan_080115_4464.png). How can I change it?
