### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by visionbike** [eezkni/UEGAN#2]
Dear,

I appreciate your great work!

I am quite curious about the dataset because preparing dataset for unsupervised learning is not an easy task (to define 'low-quality' and 'high-quality' image). Could you provide your dataset? You can send via email: ntthienphuc6195@gmail.com

Thank you so much.

**Comment by eezkni** [comment]
For the MIT-Adobe FiveK dataset, I directly used Lightroom to decode the images to png format and resized the short side of the images to 512 resolution. The 'low-quality' images are captured raw images and 'high-quality' images are from expert C. You can download the images used in our work from the following links: https://drive.google.com/drive/folders/1Jv0_9CnYxh_2ReFaVrwG19O3F7xBtdZT?usp=sharing

For the Flickr dataset, I am not sure whether I have the right to release it so you need to collect/crawl it by yourself.

Thanks.

**Comment by visionbike** [comment]
Thank you so much! Hope that you could public flickr if possible!

**Comment by ComingPeopleHW** [comment]
@eezkni Hello, what's dataset you train the 'identity loss' ? Flickr dataset you mentioned in your paper? Thank you.

**Comment by eezkni** [comment]
@ComingPeopleHW Both the MIT-Adobe FiveK dataset and Flickr dataset used the 'identity loss'. If you have any further questions, feel free to contact me via email (eezkni@gmail.com).

**Comment by visionbike** [comment]
Hi @eezkni ,
After reading your paper, I have three questions:
1) Could you explain how high-quality input can help the generator generate correct image?
2) When you train your model, do you only feed the images generated from degraded images into discriminator or you also use the images generated from high-quality ones?
3) What is your multi-scale discriminator's output? feature maps? scalar value?

Thank you
