### ISSUE TITLE
Bug in calculate PSNR value ?

### ISSUE THREAD

**Issue by ComingPeopleHW** [eezkni/UEGAN#4]
When calculate psnr during validation, generated image and GT image have different size.

**Comment by eezkni** [comment]
Please check if the size of your test image is a multiple of 2^4 (16).

**Comment by ComingPeopleHW** [comment]
> Please check if the size of your test image is a multiple of 2^4 (16).

I use dataset which you provided  to train UEGAN.
During validation, in CalcPSNR.py 37 line   `im_Gen = cv2.imread(img_path) / 255.` im_Gen(generate by G) size is (512,512) .
But in 45 line `im_GT = cv2.imread(os.path.join(folder_GT, GT_imgName)) / 255.`  im_GT(read from folder 'data/fiveK/val/label') size is (512,X) or (X,512)
So, these two image can't get a PSNR between them. Did i make a mistake?

**Comment by eezkni** [comment]
You should crop all test images to a multiple of 16. Besides, if all test images have a uniform size, the ```val_batch_size``` can be set to be greater than 1, otherwise, it should be set to 1. The cropping code has been updated to ```./metrics/CenterCrop.m```.
